/**
 * Motion Action Constants
 */
export const DRAG_IMAGE_IN_PREVIEW = "DRAG_IMAGE_IN_PREVIEW";
export const MOVE_IMAGE_LEFT = "MOVE_IMAGE_LEFT";
export const MOVE_IMAGE_RIGHT = "MOVE_IMAGE_RIGHT";
export const MOVE_IMAGE_UP = "MOVE_IMAGE_UP";
export const MOVE_IMAGE_DOWN = "MOVE_IMAGE_DOWN";
export const ROTATE_RIGHT = "ROTATE_RIGHT";
export const ROTATE_LEFT = "ROTATE_LEFT";
export const RESET_POSITIONS = "RESET_POSITIONS";
export const UPDATE_MOTION_ORDER = "UPDATE_MOTION_ORDER";
export const MID_AREA_STACK_UPDATION = "MID_AREA_STACK_UPDATION";

/**
 * Mid Area Constants
 */
export const ADD_NEW_STACK = "ADD_NEW_STACK";
export const UPDATE_EXISTING_LIST = "UPDATE_EXISTING_LIST";

/**
 * Looks Actions Constants
 */

export const SHOW_CATSPRITE = "SHOW_CATSPRITE";
export const HIDE_CATSPRITE = "HIDE_CATSPRITE";
export const SET_SIZE_CATSPRITE = "SET_SIZE_CATSPRITE";
export const SET_THINK_CLOUD_VISIBLE = "SET_THINK_CLOUD_VISIBLE";
export const SET_THINK_CLOUD_MESSAGE = "SET_THINK_CLOUD_MESSAGE";
export const SET_THINK_CLOUD_NOT_VISIBLE = "SET_THINK_CLOUD_NOT_VISIBLE";
export const UPDATE_LOOKS_ORDER = "UPDATE_LOOKS_ORDER";
